language: node_js
node_js:
- '4.3'
deploy:
  provider: npm
  email: miyoda@gmail.com
  api_key:
    secure: l4zDT86XRN8BoehCX5Tb6NJG4zXQMuSHA50XioiCGERyorkiVQ2GGXwqvNhDqDZ6ACgt8wV5uWKuD76CKsru0fNfmlyRQ+7nwuTgHKGJnGH7nU1a2obMDRLoti1qG5zee6c3YruwtaxO/0a4Y7SvEKt7RbNdsW595vDMZuyGiYIpY9kITI9Kvf/9kmzognXhhGnVDADcs51PwhMbQ2VluzTaZL5BzzrpiP3jGVesLI3Irh+f2HhPZnjKVE51OmY76NiIcqeAdcFFC0UGzsng1gdX7jjB9kuQAOKzR1tOiyQF3qitGVTN/KccsdbiWgtsZL/mFPxpYaFC7fjBOw5KA/zqkU59rGgqqdyL7MK9E97nUQ5yeTaXPjDFjyFFKrQywuRV2IQp3n/T2rEXoNyUhr2Hf78WldrQIuTvUqEQ4GPzgxpIkJs+o74jw9nC7vqFEgVbx429Oytnz3BCPDYtfMBgB5rrcTa6HYjAxvStzCrnpu7IrNSiN1aWpRBaoj+zDHGXAwu07m7MsyRPWM4vY4c7jLjmjoHkIFcxRjISnEWapmjtlo4EUlouoBSA4+XtaChZI1pe4dkbnii3EDanaYmfh2N/GZcUro/+0oORtGHsHfvfSv4diIGmfIrGVJyYgrUSbYOkGhaHBNj7u2NHiA95fcK6kc6OHU6n8e85aGE=
  on:
    tags: true
    repo: miyoda/express-middleware-apikey
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
