language: node_js
node_js:
- '4.3'
deploy:
  provider: npm
  email: miyoda@gmail.com
  api_key:
    secure: bjSiB2RB1DgoS3SV0a/wafvImGHa01DnJZYMWueRI4bjAVdC+37Z71GL3PuszSSUlE3nUh6KVJ1Qm0C7pv3qenrU6xh1tQTbkh7Vai0ydDQkZlpkygFivSxRUsK9lU+FYmjBAbvW1lBSanTlojZJZfJvdvYI+O4z6/dBPwQbeCxMBnXQxdbkUIBJbAzP4ba0jBx3iecw3HZ8bF8Ihu6+ByFk8xL5d3DqyYaYW33TqeMVVs74t7FUJFs2VMn5ul55SZDafdcEcxSDBupJo4i5c1dm9HEtARk2eSz2EbmltKFIYHR7qR1CEIqsHhhX34s7wBtjdlqufpmswFThCIUQFCXXSAGmvYo7mcLFPTY70tR+HLR/zjB4oAbFImh8POUeibzZpNxiAj+VLMVBKl87nd11hDF68RuVptOxryWhiNxWu9PknIFcgnKHJmW80ciaABahizIkHsaePWUT5tBJOf8hQZ8+O4D9CipO4PMV+kAULJl5Ksa/c0ic8s59cGlhfrnoTdfd/rACwSGEikB0eMYt5Ln5xNv+6HyjwxQNV1V/fRCGsnMLhiDTIKQiqd9OqPsPuqKSN37wZnysnRXmGuJ24Vt4fIlVIRn52oQgR0vIBZmXH41uI2Hvfk9inoHkQaDgBXJ2jpCPbedKZ+j+40PVlj7pNVxPo2WnoGMJN9c=
  on:
    tags: true
    repo: miyoda/express-middleware-apikey
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
